FROM node:16-alpine

WORKDIR /app

# Copy the package.json and package-lock.json files
COPY ./frontend/package.json /app/


# Install dependencies
RUN npm install

COPY ./frontend /app

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]






